---
- name: Create microbin user
  ansible.builtin.user:
    name: "{{ microbin_container_user }}"
    shell: /sbin/nologin
    create_home: true
    state: present
  become: true

- name: Get created user metadata
  ansible.builtin.getent:
    database: passwd
    key: "{{ microbin_container_user }}"

- name: Setting user id and group id facts
  ansible.builtin.set_fact:
    created_uid: "{{ ansible_facts.getent_passwd[microbin_container_user].1 }}"
    created_gid: "{{ ansible_facts.getent_passwd[microbin_container_user].2 }}"

- name: Ensure microbin folders exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ microbin_container_user }}"
    group: "{{ microbin_container_user }}"
    state: directory
    mode: 0755
  loop:
    - "{{ microbin_host_config_path }}"
    - "{{ microbin_host_data_path }}"

- name: Copy microbin docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ microbin_host_config_path }}/docker-compose.yml"
    owner: "{{ microbin_container_user }}"
    group: "{{ microbin_container_user }}"
    mode: 0644
  become: true

- name: Create systemd microbin service.
  ansible.builtin.template:
    src: templates/microbin.service.j2
    dest: "/etc/systemd/system/microbin.service"
    mode: 0644
  become: true

- name: Ensure microbin.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: microbin
  become: true

- name: Check microbin container
  ansible.builtin.uri:
    url: "http://localhost:{{ microbin_host_port }}"
    status_code: [200, 401]
  register: result
  until: result.status == 200 or result.status == 401
  retries: 5
  delay: 60

- name: Remove old image versions
  become: true
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
